export const AGENCY_AGENTS_ZH_INDEX: Array<{id:string;dept:string;name:string;path:string;description:string}> = [
  {"id": "engineering-frontend-developer", "dept": "engineering", "name": "前端开发者", "path": "engineering/engineering-frontend-developer.md", "description": "React/Vue、UI 实现、性能优化"},
  {"id": "engineering-backend-architect", "dept": "engineering", "name": "后端架构师", "path": "engineering/engineering-backend-architect.md", "description": "API 设计、数据库架构、可扩展性"},
  {"id": "engineering-ai-engineer", "dept": "engineering", "name": "AI 工程师", "path": "engineering/engineering-ai-engineer.md", "description": "机器学习、模型部署、AI 集成"},
  {"id": "engineering-devops-automator", "dept": "engineering", "name": "DevOps 自动化师", "path": "engineering/engineering-devops-automator.md", "description": "CI/CD、基础设施自动化"},
  {"id": "engineering-security-engineer", "dept": "engineering", "name": "安全工程师", "path": "engineering/engineering-security-engineer.md", "description": "威胁建模、代码审计、安全架构"},
  {"id": "engineering-rapid-prototyper", "dept": "engineering", "name": "快速原型师", "path": "engineering/engineering-rapid-prototyper.md", "description": "快速 POC、MVP 开发"},
  {"id": "engineering-senior-developer", "dept": "engineering", "name": "高级开发者", "path": "engineering/engineering-senior-developer.md", "description": "Laravel/Livewire/FluxUI、高端 CSS、Three.js"},
  {"id": "engineering-mobile-app-builder", "dept": "engineering", "name": "移动应用开发者", "path": "engineering/engineering-mobile-app-builder.md", "description": "iOS/Android 原生、跨平台框架"},
  {"id": "engineering-data-engineer", "dept": "engineering", "name": "数据工程师", "path": "engineering/engineering-data-engineer.md", "description": "ETL/ELT、数据湖、Spark/dbt"},
  {"id": "engineering-technical-writer", "dept": "engineering", "name": "技术文档工程师", "path": "engineering/engineering-technical-writer.md", "description": "API 文档、开发者文档、docs-as-code"},
  {"id": "engineering-autonomous-optimization-architect", "dept": "engineering", "name": "自主优化架构师", "path": "engineering/engineering-autonomous-optimization-architect.md", "description": "自适应系统、自动调优"},
  {"id": "engineering-embedded-firmware-engineer", "dept": "engineering", "name": "嵌入式固件工程师", "path": "engineering/engineering-embedded-firmware-engineer.md", "description": "RTOS、外设驱动、低功耗设计"},
  {"id": "engineering-pc-host-engineer", "dept": "engineering", "name": "上位机工程师", "path": "engineering/engineering-pc-host-engineer.md", "description": "Qt/QML、QSerialPort、Modbus/CAN、QChart 实时可视化"},
  {"id": "engineering-mechanical-design-engineer", "dept": "engineering", "name": "机械设计工程师", "path": "engineering/engineering-mechanical-design-engineer.md", "description": "传动选型、强度刚度疲劳振动校核、DFMA、GB/ISO 标准件"},
  {"id": "engineering-embedded-linux-driver-engineer", "dept": "engineering", "name": "嵌入式 Linux 驱动工程师", "path": "engineering/engineering-embedded-linux-driver-engineer.md", "description": "内核模块、设备树、Platform/I2C/SPI 驱动"},
  {"id": "engineering-fpga-digital-design-engineer", "dept": "engineering", "name": "FPGA/ASIC 数字设计工程师", "path": "engineering/engineering-fpga-digital-design-engineer.md", "description": "Verilog/SystemVerilog、时序收敛、AXI 总线"},
  {"id": "engineering-iot-solution-architect", "dept": "engineering", "name": "IoT 方案架构师", "path": "engineering/engineering-iot-solution-architect.md", "description": "MQTT/CoAP、边缘计算、设备管理、云平台"},
  {"id": "engineering-incident-response-commander", "dept": "engineering", "name": "故障响应指挥官", "path": "engineering/engineering-incident-response-commander.md", "description": "故障处置、SLO 管理、事后复盘"},
  {"id": "engineering-threat-detection-engineer", "dept": "engineering", "name": "威胁检测工程师", "path": "engineering/engineering-threat-detection-engineer.md", "description": "SIEM、威胁狩猎、检测规则"},
  {"id": "engineering-solidity-smart-contract-engineer", "dept": "engineering", "name": "Solidity 智能合约工程师", "path": "engineering/engineering-solidity-smart-contract-engineer.md", "description": "Solidity、EVM、Gas 优化、DeFi"},
  {"id": "engineering-wechat-mini-program-developer", "dept": "engineering", "name": "微信小程序开发者", "path": "engineering/engineering-wechat-mini-program-developer.md", "description": "WXML/WXSS、微信支付、云开发"},
  {"id": "engineering-code-reviewer", "dept": "engineering", "name": "代码审查员", "path": "engineering/engineering-code-reviewer.md", "description": "代码审查、安全审计、质量把关"},
  {"id": "engineering-database-optimizer", "dept": "engineering", "name": "数据库优化师", "path": "engineering/engineering-database-optimizer.md", "description": "Schema 设计、查询优化、索引策略"},
  {"id": "engineering-git-workflow-master", "dept": "engineering", "name": "Git 工作流大师", "path": "engineering/engineering-git-workflow-master.md", "description": "分支策略、约定式提交、变基"},
  {"id": "engineering-software-architect", "dept": "engineering", "name": "软件架构师", "path": "engineering/engineering-software-architect.md", "description": "系统设计、DDD、架构决策"},
  {"id": "engineering-sre", "dept": "engineering", "name": "SRE (站点可靠性工程师)", "path": "engineering/engineering-sre.md", "description": "SLO、可观测性、混沌工程"},
  {"id": "engineering-ai-data-remediation-engineer", "dept": "engineering", "name": "AI 数据修复工程师", "path": "engineering/engineering-ai-data-remediation-engineer.md", "description": "自愈管道、SLM 语义聚类、零数据丢失"},
  {"id": "engineering-feishu-integration-developer", "dept": "engineering", "name": "飞书集成开发工程师", "path": "engineering/engineering-feishu-integration-developer.md", "description": "飞书机器人、审批流、多维表格"},
  {"id": "engineering-dingtalk-integration-developer", "dept": "engineering", "name": "钉钉集成开发工程师", "path": "engineering/engineering-dingtalk-integration-developer.md", "description": "钉钉机器人、酷应用、连接器"},
  {"id": "engineering-cms-developer", "dept": "engineering", "name": "CMS 开发者", "path": "engineering/engineering-cms-developer.md", "description": "Drupal/WordPress、主题开发、自定义插件"},
  {"id": "engineering-email-intelligence-engineer", "dept": "engineering", "name": "邮件智能工程师", "path": "engineering/engineering-email-intelligence-engineer.md", "description": "邮件解析、结构化提取、AI 推理数据"},
  {"id": "engineering-filament-optimization-specialist", "dept": "engineering", "name": "Filament 优化专家", "path": "engineering/engineering-filament-optimization-specialist.md", "description": "Filament PHP 后台重构、高影响力改造"},
  {"id": "design-ui-designer", "dept": "design", "name": "UI 设计师", "path": "design/design-ui-designer.md", "description": "视觉设计、组件库、设计系统"},
  {"id": "design-ux-researcher", "dept": "design", "name": "UX 研究员", "path": "design/design-ux-researcher.md", "description": "用户测试、行为分析"},
  {"id": "design-ux-architect", "dept": "design", "name": "UX 架构师", "path": "design/design-ux-architect.md", "description": "信息架构、交互设计、导航系统"},
  {"id": "design-brand-guardian", "dept": "design", "name": "品牌守护者", "path": "design/design-brand-guardian.md", "description": "品牌标识、一致性、定位"},
  {"id": "design-image-prompt-engineer", "dept": "design", "name": "图像提示词工程师", "path": "design/design-image-prompt-engineer.md", "description": "AI 图像生成、提示词优化"},
  {"id": "design-visual-storyteller", "dept": "design", "name": "视觉叙事师", "path": "design/design-visual-storyteller.md", "description": "数据可视化、视觉叙事"},
  {"id": "design-whimsy-injector", "dept": "design", "name": "趣味注入师", "path": "design/design-whimsy-injector.md", "description": "微交互、彩蛋、趣味元素"},
  {"id": "design-inclusive-visuals-specialist", "dept": "design", "name": "包容性视觉专家", "path": "design/design-inclusive-visuals-specialist.md", "description": "多元化视觉、无障碍设计"},
  {"id": "marketing-xiaohongshu-operator", "dept": "marketing", "name": "小红书运营专家", "path": "marketing/marketing-xiaohongshu-operator.md", "description": "种草笔记、达人合作、爆款内容"},
  {"id": "marketing-douyin-strategist", "dept": "marketing", "name": "抖音策略师", "path": "marketing/marketing-douyin-strategist.md", "description": "短视频策划、算法优化、直播带货"},
  {"id": "marketing-wechat-operator", "dept": "marketing", "name": "微信公众号运营", "path": "marketing/marketing-wechat-operator.md", "description": "公众号内容、社群运营、裂变增长"},
  {"id": "marketing-bilibili-strategist", "dept": "marketing", "name": "B站内容策略师", "path": "marketing/marketing-bilibili-strategist.md", "description": "UP主运营、弹幕文化、中长视频"},
  {"id": "marketing-kuaishou-strategist", "dept": "marketing", "name": "快手策略师", "path": "marketing/marketing-kuaishou-strategist.md", "description": "下沉市场、老铁文化、直播电商"},
  {"id": "marketing-china-ecommerce-operator", "dept": "marketing", "name": "中国电商运营专家", "path": "marketing/marketing-china-ecommerce-operator.md", "description": "淘宝/拼多多/京东、广告投放、大促作战"},
  {"id": "marketing-ecommerce-operator", "dept": "marketing", "name": "电商运营师", "path": "marketing/marketing-ecommerce-operator.md", "description": "淘宝/拼多多/京东、直播带货、大促"},
  {"id": "marketing-baidu-seo-specialist", "dept": "marketing", "name": "百度 SEO 专家", "path": "marketing/marketing-baidu-seo-specialist.md", "description": "百度优化、百科/知道/贴吧生态"},
  {"id": "marketing-private-domain-operator", "dept": "marketing", "name": "私域流量运营师", "path": "marketing/marketing-private-domain-operator.md", "description": "企微SCRM、社群运营、用户生命周期"},
  {"id": "marketing-livestream-commerce-coach", "dept": "marketing", "name": "直播电商主播教练", "path": "marketing/marketing-livestream-commerce-coach.md", "description": "直播话术、选品排品、千川投放"},
  {"id": "marketing-cross-border-ecommerce", "dept": "marketing", "name": "跨境电商运营专家", "path": "marketing/marketing-cross-border-ecommerce.md", "description": "Amazon/Shopee/Lazada、海外仓、品牌出海"},
  {"id": "marketing-short-video-editing-coach", "dept": "marketing", "name": "短视频剪辑指导师", "path": "marketing/marketing-short-video-editing-coach.md", "description": "剪映/PR/达芬奇、调色、音频、特效"},
  {"id": "marketing-weibo-strategist", "dept": "marketing", "name": "微博运营策略师", "path": "marketing/marketing-weibo-strategist.md", "description": "热搜运营、超话、舆情公关、粉丝经济"},
  {"id": "marketing-podcast-strategist", "dept": "marketing", "name": "播客内容策略师", "path": "marketing/marketing-podcast-strategist.md", "description": "小宇宙/喜马拉雅、音频制作、商业化"},
  {"id": "marketing-weixin-channels-strategist", "dept": "marketing", "name": "微信视频号运营策略师", "path": "marketing/marketing-weixin-channels-strategist.md", "description": "视频号直播、社交裂变、私域闭环"},
  {"id": "marketing-knowledge-commerce-strategist", "dept": "marketing", "name": "知识付费产品策划师", "path": "marketing/marketing-knowledge-commerce-strategist.md", "description": "得到/知识星球/小鹅通、内容定价"},
  {"id": "marketing-xiaohongshu-specialist", "dept": "marketing", "name": "小红书专家", "path": "marketing/marketing-xiaohongshu-specialist.md", "description": "生活方式内容、趋势策略"},
  {"id": "marketing-wechat-official-account", "dept": "marketing", "name": "微信公众号管理", "path": "marketing/marketing-wechat-official-account.md", "description": "订阅者运营、内容营销"},
  {"id": "marketing-zhihu-strategist", "dept": "marketing", "name": "知乎策略师", "path": "marketing/marketing-zhihu-strategist.md", "description": "知识型内容、思想领袖建设"},
  {"id": "marketing-china-market-localization-strategist", "dept": "marketing", "name": "中国市场本地化策略师", "path": "marketing/marketing-china-market-localization-strategist.md", "description": "抖音/小红书/微信/B站全栈本地化"},
  {"id": "marketing-daily-news-briefing", "dept": "marketing", "name": "新闻情报官", "path": "marketing/marketing-daily-news-briefing.md", "description": "国内外多源新闻采集、交叉验证、结构化简报"},
  {"id": "marketing-tiktok-strategist", "dept": "marketing", "name": "TikTok 策略师", "path": "marketing/marketing-tiktok-strategist.md", "description": "病毒式内容、算法优化"},
  {"id": "marketing-twitter-engager", "dept": "marketing", "name": "Twitter 互动官", "path": "marketing/marketing-twitter-engager.md", "description": "实时互动、思想领袖"},
  {"id": "marketing-instagram-curator", "dept": "marketing", "name": "Instagram 策展师", "path": "marketing/marketing-instagram-curator.md", "description": "视觉叙事、社区运营"},
  {"id": "marketing-reddit-community-builder", "dept": "marketing", "name": "Reddit 社区运营", "path": "marketing/marketing-reddit-community-builder.md", "description": "社区文化、真实互动"},
  {"id": "marketing-app-store-optimizer", "dept": "marketing", "name": "应用商店优化师", "path": "marketing/marketing-app-store-optimizer.md", "description": "ASO、转化优化"},
  {"id": "marketing-video-optimization-specialist", "dept": "marketing", "name": "视频优化专家", "path": "marketing/marketing-video-optimization-specialist.md", "description": "YouTube 算法、观众留存、跨平台分发"},
  {"id": "marketing-growth-hacker", "dept": "marketing", "name": "增长黑客", "path": "marketing/marketing-growth-hacker.md", "description": "快速获客、病毒循环、实验"},
  {"id": "marketing-content-creator", "dept": "marketing", "name": "内容创作者", "path": "marketing/marketing-content-creator.md", "description": "多平台内容、编辑日历"},
  {"id": "marketing-social-media-strategist", "dept": "marketing", "name": "社交媒体策略师", "path": "marketing/marketing-social-media-strategist.md", "description": "跨平台策略、整合营销"},
  {"id": "marketing-seo-specialist", "dept": "marketing", "name": "SEO 专家", "path": "marketing/marketing-seo-specialist.md", "description": "搜索引擎优化、技术 SEO"},
  {"id": "marketing-carousel-growth-engine", "dept": "marketing", "name": "轮播图增长引擎", "path": "marketing/marketing-carousel-growth-engine.md", "description": "轮播图内容、自动化投放"},
  {"id": "marketing-linkedin-content-creator", "dept": "marketing", "name": "LinkedIn 内容创作专家", "path": "marketing/marketing-linkedin-content-creator.md", "description": "LinkedIn 职场内容、B2B 获客"},
  {"id": "marketing-book-co-author", "dept": "marketing", "name": "图书联合作者", "path": "marketing/marketing-book-co-author.md", "description": "思想领袖力图书、代笔协作"},
  {"id": "marketing-ai-citation-strategist", "dept": "marketing", "name": "AI 引文策略师", "path": "marketing/marketing-ai-citation-strategist.md", "description": "AEO/GEO 优化、AI 平台可见性审计"},
  {"id": "paid-media-auditor", "dept": "paid-media", "name": "付费媒体审计师", "path": "paid-media/paid-media-auditor.md", "description": "广告账户审计、预算优化"},
  {"id": "paid-media-creative-strategist", "dept": "paid-media", "name": "广告创意策略师", "path": "paid-media/paid-media-creative-strategist.md", "description": "广告素材策划、A/B 测试"},
  {"id": "paid-media-paid-social-strategist", "dept": "paid-media", "name": "社交广告策略师", "path": "paid-media/paid-media-paid-social-strategist.md", "description": "社交平台广告投放"},
  {"id": "paid-media-ppc-strategist", "dept": "paid-media", "name": "PPC 竞价策略师", "path": "paid-media/paid-media-ppc-strategist.md", "description": "搜索竞价、关键词管理"},
  {"id": "paid-media-programmatic-buyer", "dept": "paid-media", "name": "程序化广告采买专家", "path": "paid-media/paid-media-programmatic-buyer.md", "description": "DSP、RTB、程序化购买"},
  {"id": "paid-media-search-query-analyst", "dept": "paid-media", "name": "搜索词分析师", "path": "paid-media/paid-media-search-query-analyst.md", "description": "搜索词挖掘、否词优化"},
  {"id": "paid-media-tracking-specialist", "dept": "paid-media", "name": "追踪与归因专家", "path": "paid-media/paid-media-tracking-specialist.md", "description": "转化追踪、归因模型"},
  {"id": "sales-account-strategist", "dept": "sales", "name": "客户拓展策略师", "path": "sales/sales-account-strategist.md", "description": "大客户拓展、ABM 策略"},
  {"id": "sales-coach", "dept": "sales", "name": "销售教练", "path": "sales/sales-coach.md", "description": "销售辅导、技能提升"},
  {"id": "sales-deal-strategist", "dept": "sales", "name": "赢单策略师", "path": "sales/sales-deal-strategist.md", "description": "成交策略、MEDDPICC"},
  {"id": "sales-discovery-coach", "dept": "sales", "name": "Discovery 教练", "path": "sales/sales-discovery-coach.md", "description": "需求挖掘、客户洞察"},
  {"id": "sales-engineer", "dept": "sales", "name": "售前工程师", "path": "sales/sales-engineer.md", "description": "技术方案、Demo 演示"},
  {"id": "sales-outbound-strategist", "dept": "sales", "name": "Outbound 策略师", "path": "sales/sales-outbound-strategist.md", "description": "外呼策略、Cold outreach"},
  {"id": "sales-pipeline-analyst", "dept": "sales", "name": "Pipeline 分析师", "path": "sales/sales-pipeline-analyst.md", "description": "销售漏斗、预测分析"},
  {"id": "sales-proposal-strategist", "dept": "sales", "name": "投标策略师", "path": "sales/sales-proposal-strategist.md", "description": "投标方案、提案撰写"},
  {"id": "finance-financial-forecaster", "dept": "finance", "name": "财务预测分析师", "path": "finance/finance-financial-forecaster.md", "description": "收入预测、场景建模、现金流"},
  {"id": "finance-invoice-manager", "dept": "finance", "name": "发票管理专家", "path": "finance/finance-invoice-manager.md", "description": "增值税发票、金税系统、三单匹配"},
  {"id": "finance-fraud-detector", "dept": "finance", "name": "金融风控分析师", "path": "finance/finance-fraud-detector.md", "description": "交易风控、反洗钱、电信诈骗"},
  {"id": "hr-recruiter", "dept": "hr", "name": "招聘专家", "path": "hr/hr-recruiter.md", "description": "Boss直聘/猎聘、校招社招、背调"},
  {"id": "hr-performance-reviewer", "dept": "hr", "name": "绩效管理专家", "path": "hr/hr-performance-reviewer.md", "description": "OKR/KPI、361分布、晋升答辩"},
  {"id": "legal-contract-reviewer", "dept": "legal", "name": "合同审查专家", "path": "legal/legal-contract-reviewer.md", "description": "民法典合同编、电子签章、风险评估"},
  {"id": "legal-policy-writer", "dept": "legal", "name": "制度文件撰写专家", "path": "legal/legal-policy-writer.md", "description": "PIPL/数据安全法、隐私政策"},
  {"id": "supply-chain-inventory-forecaster", "dept": "supply-chain", "name": "库存预测专家", "path": "supply-chain/supply-chain-inventory-forecaster.md", "description": "需求预测、安全库存、618/双11备货"},
  {"id": "supply-chain-vendor-evaluator", "dept": "supply-chain", "name": "供应商评估专家", "path": "supply-chain/supply-chain-vendor-evaluator.md", "description": "1688供应商、验厂、国标质检"},
  {"id": "supply-chain-route-optimizer", "dept": "supply-chain", "name": "物流路线优化师", "path": "supply-chain/supply-chain-route-optimizer.md", "description": "顺丰/通达系、冷链、跨境物流"},
  {"id": "supply-chain-strategist", "dept": "supply-chain", "name": "供应链采购策略师", "path": "supply-chain/supply-chain-strategist.md", "description": "1688采购、质检、供应商管理、ERP"},
  {"id": "product-sprint-prioritizer", "dept": "product", "name": "Sprint 排序师", "path": "product/product-sprint-prioritizer.md", "description": "敏捷规划、功能优先级"},
  {"id": "product-trend-researcher", "dept": "product", "name": "趋势研究员", "path": "product/product-trend-researcher.md", "description": "市场情报、竞品分析"},
  {"id": "product-feedback-synthesizer", "dept": "product", "name": "反馈分析师", "path": "product/product-feedback-synthesizer.md", "description": "用户反馈分析、洞察提取"},
  {"id": "product-behavioral-nudge-engine", "dept": "product", "name": "行为助推引擎", "path": "product/product-behavioral-nudge-engine.md", "description": "行为心理学、用户引导"},
  {"id": "product-manager", "dept": "product", "name": "产品经理", "path": "product/product-manager.md", "description": "产品全生命周期、PRD、路线图"},
  {"id": "project-manager-senior", "dept": "project-management", "name": "高级项目经理", "path": "project-management/project-manager-senior.md", "description": "需求拆解、范围管控"},
  {"id": "project-management-project-shepherd", "dept": "project-management", "name": "项目牧羊人", "path": "project-management/project-management-project-shepherd.md", "description": "跨团队协调、进度跟踪"},
  {"id": "project-management-experiment-tracker", "dept": "project-management", "name": "实验追踪员", "path": "project-management/project-management-experiment-tracker.md", "description": "A/B 测试、实验管理"},
  {"id": "project-management-studio-producer", "dept": "project-management", "name": "工作室制片人", "path": "project-management/project-management-studio-producer.md", "description": "创意项目管理、资源调度"},
  {"id": "project-management-studio-operations", "dept": "project-management", "name": "工作室运营", "path": "project-management/project-management-studio-operations.md", "description": "工作室日常运营管理"},
  {"id": "project-management-jira-workflow-steward", "dept": "project-management", "name": "Jira 工作流管家", "path": "project-management/project-management-jira-workflow-steward.md", "description": "Jira 配置、工作流优化"},
  {"id": "testing-evidence-collector", "dept": "testing", "name": "证据收集者", "path": "testing/testing-evidence-collector.md", "description": "截图 QA、视觉验证"},
  {"id": "testing-reality-checker", "dept": "testing", "name": "现实检验者", "path": "testing/testing-reality-checker.md", "description": "证据驱动认证、质量关卡"},
  {"id": "testing-api-tester", "dept": "testing", "name": "API 测试员", "path": "testing/testing-api-tester.md", "description": "API 验证、集成测试"},
  {"id": "testing-performance-benchmarker", "dept": "testing", "name": "性能基准师", "path": "testing/testing-performance-benchmarker.md", "description": "性能测试、优化"},
  {"id": "testing-accessibility-auditor", "dept": "testing", "name": "无障碍审核员", "path": "testing/testing-accessibility-auditor.md", "description": "WCAG 审核、辅助技术测试"},
  {"id": "testing-test-results-analyzer", "dept": "testing", "name": "测试结果分析师", "path": "testing/testing-test-results-analyzer.md", "description": "测试数据分析、质量度量"},
  {"id": "testing-tool-evaluator", "dept": "testing", "name": "工具评估师", "path": "testing/testing-tool-evaluator.md", "description": "工具选型、功能对比"},
  {"id": "testing-workflow-optimizer", "dept": "testing", "name": "工作流优化师", "path": "testing/testing-workflow-optimizer.md", "description": "流程分析、自动化"},
  {"id": "testing-embedded-qa-engineer", "dept": "testing", "name": "嵌入式测试工程师", "path": "testing/testing-embedded-qa-engineer.md", "description": "HIL 测试、固件自动化测试、EMC 测试"},
  {"id": "support-support-responder", "dept": "support", "name": "客服响应者", "path": "support/support-support-responder.md", "description": "客户服务、工单处理"},
  {"id": "support-analytics-reporter", "dept": "support", "name": "数据分析师", "path": "support/support-analytics-reporter.md", "description": "数据分析、仪表盘"},
  {"id": "support-legal-compliance-checker", "dept": "support", "name": "法务合规员", "path": "support/support-legal-compliance-checker.md", "description": "合规审查、法规检查"},
  {"id": "support-executive-summary-generator", "dept": "support", "name": "高管摘要师", "path": "support/support-executive-summary-generator.md", "description": "业务摘要、战略沟通"},
  {"id": "support-finance-tracker", "dept": "support", "name": "财务追踪员", "path": "support/support-finance-tracker.md", "description": "财务分析、预算管理"},
  {"id": "support-infrastructure-maintainer", "dept": "support", "name": "基础设施运维师", "path": "support/support-infrastructure-maintainer.md", "description": "系统运维、可靠性工程"},
  {"id": "support-recruitment-specialist", "dept": "support", "name": "招聘运营专家", "path": "support/support-recruitment-specialist.md", "description": "Boss直聘/猎聘、劳动法、校招社招"},
  {"id": "agents-orchestrator", "dept": "specialized", "name": "智能体编排者", "path": "specialized/agents-orchestrator.md", "description": "多智能体协调、工作流管理"},
  {"id": "prompt-engineer", "dept": "specialized", "name": "提示词工程师", "path": "specialized/prompt-engineer.md", "description": "LLM 提示词设计、优化、评测"},
  {"id": "agentic-identity-trust", "dept": "specialized", "name": "身份信任架构师", "path": "specialized/agentic-identity-trust.md", "description": "AI 身份验证、信任框架"},
  {"id": "data-consolidation-agent", "dept": "specialized", "name": "数据整合师", "path": "specialized/data-consolidation-agent.md", "description": "多源数据整合、仪表盘"},
  {"id": "lsp-index-engineer", "dept": "specialized", "name": "LSP 索引工程师", "path": "specialized/lsp-index-engineer.md", "description": "代码智能、语义索引"},
  {"id": "report-distribution-agent", "dept": "specialized", "name": "报告分发师", "path": "specialized/report-distribution-agent.md", "description": "报告分发、多渠道推送"},
  {"id": "sales-data-extraction-agent", "dept": "specialized", "name": "销售数据提取师", "path": "specialized/sales-data-extraction-agent.md", "description": "销售数据采集、结构化"},
  {"id": "compliance-auditor", "dept": "specialized", "name": "合规审计师", "path": "specialized/compliance-auditor.md", "description": "SOC 2/ISO 27001/HIPAA 合规"},
  {"id": "accounts-payable-agent", "dept": "specialized", "name": "应付账款智能体", "path": "specialized/accounts-payable-agent.md", "description": "发票处理、付款自动化"},
  {"id": "identity-graph-operator", "dept": "specialized", "name": "身份图谱操作员", "path": "specialized/identity-graph-operator.md", "description": "身份解析、多源匹配"},
  {"id": "specialized-cultural-intelligence-strategist", "dept": "specialized", "name": "文化智能策略师", "path": "specialized/specialized-cultural-intelligence-strategist.md", "description": "文化洞察、跨文化设计"},
  {"id": "specialized-developer-advocate", "dept": "specialized", "name": "开发者布道师", "path": "specialized/specialized-developer-advocate.md", "description": "开发者关系、DX 工程"},
  {"id": "specialized-model-qa", "dept": "specialized", "name": "模型 QA 专家", "path": "specialized/specialized-model-qa.md", "description": "ML 模型审计、质量验证"},
  {"id": "zk-steward", "dept": "specialized", "name": "ZK 管家", "path": "specialized/zk-steward.md", "description": "Zettelkasten 知识管理"},
  {"id": "blockchain-security-auditor", "dept": "specialized", "name": "区块链安全审计师", "path": "specialized/blockchain-security-auditor.md", "description": "智能合约审计、漏洞检测"},
  {"id": "study-abroad-advisor", "dept": "specialized", "name": "留学规划顾问", "path": "specialized/study-abroad-advisor.md", "description": "多国申请策略、选校定位"},
  {"id": "government-digital-presales-consultant", "dept": "specialized", "name": "政务数字化售前顾问", "path": "specialized/government-digital-presales-consultant.md", "description": "方案设计、标书、等保/信创"},
  {"id": "corporate-training-designer", "dept": "specialized", "name": "企业培训课程设计师", "path": "specialized/corporate-training-designer.md", "description": "ADDIE/SAM、企业学习平台、TTT"},
  {"id": "specialized-mcp-builder", "dept": "specialized", "name": "MCP 构建器", "path": "specialized/specialized-mcp-builder.md", "description": "MCP 服务器、工具设计、API 集成"},
  {"id": "specialized-document-generator", "dept": "specialized", "name": "文档生成器", "path": "specialized/specialized-document-generator.md", "description": "PDF/PPTX/DOCX/XLSX 生成"},
  {"id": "specialized-workflow-architect", "dept": "specialized", "name": "工作流架构师", "path": "specialized/specialized-workflow-architect.md", "description": "工作流树设计、交接契约、故障恢复"},
  {"id": "automation-governance-architect", "dept": "specialized", "name": "自动化治理架构师", "path": "specialized/automation-governance-architect.md", "description": "自动化审计、n8n 工作流治理、风险评估"},
  {"id": "specialized-salesforce-architect", "dept": "specialized", "name": "Salesforce 架构师", "path": "specialized/specialized-salesforce-architect.md", "description": "Salesforce 多云设计、集成、数据模型"},
  {"id": "healthcare-marketing-compliance", "dept": "specialized", "name": "医疗健康营销合规师", "path": "specialized/healthcare-marketing-compliance.md", "description": "医疗广告法、NMPA、互联网医疗"},
  {"id": "gaokao-college-advisor", "dept": "specialized", "name": "高考志愿填报顾问", "path": "specialized/gaokao-college-advisor.md", "description": "平行志愿、位次法、冲稳保策略"},
  {"id": "specialized-pricing-optimizer", "dept": "specialized", "name": "动态定价策略师", "path": "specialized/specialized-pricing-optimizer.md", "description": "淘宝/京东/拼多多定价、大促机制"},
  {"id": "specialized-ai-policy-writer", "dept": "specialized", "name": "AI 治理政策专家", "path": "specialized/specialized-ai-policy-writer.md", "description": "算法备案、生成式AI管理、伦理审查"},
  {"id": "specialized-risk-assessor", "dept": "specialized", "name": "企业风险评估师", "path": "specialized/specialized-risk-assessor.md", "description": "COSO本土化、国企风控、ESG"},
  {"id": "specialized-meeting-assistant", "dept": "specialized", "name": "会议效率专家", "path": "specialized/specialized-meeting-assistant.md", "description": "飞书/钉钉/腾讯会议、OKR周会"},
  {"id": "specialized-civil-engineer", "dept": "specialized", "name": "土木工程师", "path": "specialized/specialized-civil-engineer.md", "description": "Eurocode/DIN/ACI/GB 多标准结构分析"},
  {"id": "specialized-french-consulting-market", "dept": "specialized", "name": "法国咨询市场专家", "path": "specialized/specialized-french-consulting-market.md", "description": "ESN/SI 生态、Malt 平台、薪资代管"},
  {"id": "specialized-korean-business-navigator", "dept": "specialized", "name": "韩国商务专家", "path": "specialized/specialized-korean-business-navigator.md", "description": "품의流程、KakaoTalk 礼仪、层级关系"},
  {"id": "recruitment-specialist", "dept": "specialized", "name": "招聘专家", "path": "specialized/recruitment-specialist.md", "description": "国内招聘平台、人才评估、劳动法合规"},
  {"id": "technical-translator-agent", "dept": "specialized", "name": "技术翻译专家", "path": "specialized/technical-translator-agent.md", "description": "中英文双向翻译、编程/AI/云计算术语"},
  {"id": "visionos-spatial-engineer", "dept": "spatial-computing", "name": "visionOS 空间工程师", "path": "spatial-computing/visionos-spatial-engineer.md", "description": "visionOS、SwiftUI 空间 UI"},
  {"id": "macos-spatial-metal-engineer", "dept": "spatial-computing", "name": "macOS Metal 空间工程师", "path": "spatial-computing/macos-spatial-metal-engineer.md", "description": "Metal、GPU 渲染"},
  {"id": "xr-interface-architect", "dept": "spatial-computing", "name": "XR 界面架构师", "path": "spatial-computing/xr-interface-architect.md", "description": "空间 UI 架构、交互设计"},
  {"id": "xr-immersive-developer", "dept": "spatial-computing", "name": "XR 沉浸式开发者", "path": "spatial-computing/xr-immersive-developer.md", "description": "WebXR、沉浸式体验"},
  {"id": "xr-cockpit-interaction-specialist", "dept": "spatial-computing", "name": "XR 座舱交互专家", "path": "spatial-computing/xr-cockpit-interaction-specialist.md", "description": "座舱 UI、多模态交互"},
  {"id": "terminal-integration-specialist", "dept": "spatial-computing", "name": "终端集成专家", "path": "spatial-computing/terminal-integration-specialist.md", "description": "终端模拟、系统集成"},
  {"id": "game-designer", "dept": "game-development", "name": "游戏设计师", "path": "game-development/game-designer.md", "description": "游戏机制、系统设计、平衡性"},
  {"id": "level-designer", "dept": "game-development", "name": "关卡设计师", "path": "game-development/level-designer.md", "description": "关卡布局、节奏控制、空间叙事"},
  {"id": "narrative-designer", "dept": "game-development", "name": "叙事设计师", "path": "game-development/narrative-designer.md", "description": "剧情设计、对话系统、世界观"},
  {"id": "technical-artist", "dept": "game-development", "name": "技术美术", "path": "game-development/technical-artist.md", "description": "Shader、渲染管线、美术工具"},
  {"id": "game-audio-engineer", "dept": "game-development", "name": "游戏音频工程师", "path": "game-development/game-audio-engineer.md", "description": "音效设计、音频引擎、空间音频"},
  {"id": "unity-architect", "dept": "game-development", "name": "Unity 架构师", "path": "game-development/unity/unity-architect.md", "description": "Unity 架构、ECS、性能优化"},
  {"id": "unity-editor-tool-developer", "dept": "game-development", "name": "Unity 编辑器工具开发者", "path": "game-development/unity/unity-editor-tool-developer.md", "description": "编辑器扩展、自定义工具"},
  {"id": "unity-multiplayer-engineer", "dept": "game-development", "name": "Unity 多人游戏工程师", "path": "game-development/unity/unity-multiplayer-engineer.md", "description": "Netcode、同步、网络架构"},
  {"id": "unity-shader-graph-artist", "dept": "game-development", "name": "Unity Shader Graph 美术师", "path": "game-development/unity/unity-shader-graph-artist.md", "description": "Shader Graph、URP/HDRP"},
  {"id": "unreal-multiplayer-architect", "dept": "game-development", "name": "Unreal 多人游戏架构师", "path": "game-development/unreal-engine/unreal-multiplayer-architect.md", "description": "Replication、网络同步"},
  {"id": "unreal-systems-engineer", "dept": "game-development", "name": "Unreal 系统工程师", "path": "game-development/unreal-engine/unreal-systems-engineer.md", "description": "Gameplay 框架、C++ 系统"},
  {"id": "unreal-technical-artist", "dept": "game-development", "name": "Unreal 技术美术", "path": "game-development/unreal-engine/unreal-technical-artist.md", "description": "材质、Niagara、渲染管线"},
  {"id": "unreal-world-builder", "dept": "game-development", "name": "Unreal 世界构建师", "path": "game-development/unreal-engine/unreal-world-builder.md", "description": "开放世界、地形、关卡串流"},
  {"id": "blender-addon-engineer", "dept": "game-development", "name": "Blender 插件工程师", "path": "game-development/blender/blender-addon-engineer.md", "description": "Python 插件、资源验证、导出自动化"},
  {"id": "godot-gameplay-scripter", "dept": "game-development", "name": "Godot 游戏脚本开发者", "path": "game-development/godot/godot-gameplay-scripter.md", "description": "GDScript、场景树、信号系统"},
  {"id": "godot-multiplayer-engineer", "dept": "game-development", "name": "Godot 多人游戏工程师", "path": "game-development/godot/godot-multiplayer-engineer.md", "description": "MultiplayerAPI、网络同步"},
  {"id": "godot-shader-developer", "dept": "game-development", "name": "Godot Shader 开发者", "path": "game-development/godot/godot-shader-developer.md", "description": "Godot Shader Language、视觉效果"},
  {"id": "roblox-avatar-creator", "dept": "game-development", "name": "Roblox 虚拟形象创作者", "path": "game-development/roblox-studio/roblox-avatar-creator.md", "description": "虚拟形象、UGC 资产"},
  {"id": "roblox-experience-designer", "dept": "game-development", "name": "Roblox 体验设计师", "path": "game-development/roblox-studio/roblox-experience-designer.md", "description": "体验设计、游戏循环"},
  {"id": "roblox-systems-scripter", "dept": "game-development", "name": "Roblox 系统脚本工程师", "path": "game-development/roblox-studio/roblox-systems-scripter.md", "description": "Luau 脚本、数据存储"},
  {"id": "academic-anthropologist", "dept": "academic", "name": "人类学家", "path": "academic/academic-anthropologist.md", "description": "文化体系、仪式、民族志"},
  {"id": "academic-geographer", "dept": "academic", "name": "地理学家", "path": "academic/academic-geographer.md", "description": "自然与人文地理、空间分析"},
  {"id": "academic-historian", "dept": "academic", "name": "历史学家", "path": "academic/academic-historian.md", "description": "历史分析、史料考证"},
  {"id": "academic-narratologist", "dept": "academic", "name": "叙事学家", "path": "academic/academic-narratologist.md", "description": "叙事理论、故事结构"},
  {"id": "academic-psychologist", "dept": "academic", "name": "心理学家", "path": "academic/academic-psychologist.md", "description": "行为心理、人格理论"},
  {"id": "academic-study-planner", "dept": "academic", "name": "学习规划师", "path": "academic/academic-study-planner.md", "description": "考研/考公/法考备考、学习方法论"},
  {"id": "EXECUTIVE-BRIEF", "dept": "strategy", "name": "高管简报", "path": "strategy/EXECUTIVE-BRIEF.md", "description": "NEXUS 战略概览"},
  {"id": "QUICKSTART", "dept": "strategy", "name": "快速上手", "path": "strategy/QUICKSTART.md", "description": "5 分钟上手指南"},
  {"id": "nexus-strategy", "dept": "strategy", "name": "完整战略", "path": "strategy/nexus-strategy.md", "description": "运营纲领全文"}
];
